version: '3.8'

services:
  my-app:
    image: m65535/web-service:latest  
    ports:
      - "80:4000"
    deploy:
      mode: replicated
      replicas: 2
      # Дополнительные настройки развертывания (опционально)
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.128'
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s